### ISSUE TITLE
Junction cannot find CX5 NIC bound to vfio-pci

### ISSUE THREAD

**Issue by chenyoumin1993** [JunctionOS/junction#1]
### Hardware configuration
OS: Ubuntu 22.04 w/ Linux 5.19.0-50-generic
NIC: ConnectX-5 (100Gbps) in IB mode; MLNX_OFED_LINUX-23.10-3.2.2.0
GCC: 12.3.0
CPU: Intel(R) Xeon(R) Gold 6330 x2
DDR: 96GB

### Problem discription
I can successfully bind the NIC to the vfio-pci driver, but the device cannot be found when I start the core scheduler with `./lib/caladan/iokerneld ias vfio nicpci 0000:4b:00.0`, which fails at [here](https://github.com/shenango/caladan/blob/d636c0fd4b9e00c8e5ff9093a5c5b40a71edaf53/iokernel/directpath/core.c#L1249).
![image](https://github.com/user-attachments/assets/39850b49-9cc5-421b-8bc1-b2df0bdfe240)

![image](https://github.com/user-attachments/assets/eb7dd7bd-cfd4-49de-bca0-4c2ca8f66575)

![image](https://github.com/user-attachments/assets/61f71342-cbc7-488c-a978-38302eae5c30)

I have also tried to switch CX5 to ETH mode and the iokernel can be launched only when `directpath` is disabled.

Moreover, I have run the apps included in the DPDK repo (e.g., dpdk-testpmd), and the same problem occurs (ALL necessary kernel models are loaded already)
![image](https://github.com/user-attachments/assets/602bdb96-08a0-4d6f-893f-5eade2e3d259)

**Comment by chenyoumin1993** [comment]
Btw, iommu is disabled on our platform, so I use `echo 1 > /sys/module/vfio/parameters/enable_unsafe_noiommu_mode` before binding the device the vfio-pci.

I just tried to re-enable iommu, and now iokernel can find the device successfully. However, a new problem occurs at [here](https://github.com/shenango/caladan/blob/d636c0fd4b9e00c8e5ff9093a5c5b40a71edaf53/iokernel/directpath/core.c#L255), where `mlx5dv_devx_general_cmd` returns an errno of 121 (CX5 firmware version: 16.35.4030)
<img width="375" alt="1af34ad4747c02f9d78eb247643600d" src="https://github.com/user-attachments/assets/21641397-6922-4136-9cee-2217d16ca11d" />

**Comment by joshuafried** [comment]
Hello, to use a CX5 NIC it must be in Ethernet mode. The vfio mode also currently requires the IOMMU to be fully enabled. You should be able to run with your CX5 without vfio (leave it bound to mlx5_core and omit the vfio parameter from the iokernel).

**Comment by joshuafried** [comment]
The last error you got with the IOMMU enabled is because the port is in IB mode, can you switch it to Ethernet again?

**Comment by chenyoumin1993** [comment]
Thank you for your kind response. Indeed, the iokernel can be launched with both IOMMU and Ethernet modes enabled.
